export const categories = [
  { id: 1, category_name: "Trending", icon: "" },
  { id: 2, category_name: "Music", icon: "" },
  { id: 3, category_name: "Technology", icon: "" },
  { id: 4, category_name: "Science", icon: "" },
  { id: 5, category_name: "Movies", icon: "" },
  { id: 6, category_name: "Education", icon: "" },
  { id: 7, category_name: "Podcast", icon: "" },
  { id: 8, category_name: "Gaming", icon: "" },
  { id: 9, category_name: "Cooking", icon: "" },
  { id: 10, category_name: "News", icon: "" },
  { id: 11, category_name: "Politics", icon: "" },
  { id: 12, category_name: "Sports", icon: "" },
  { id: 13, category_name: "Fashion", icon: "" },
  { id: 14, category_name: "Comedy", icon: "" },
  { id: 15, category_name: "Health", icon: "" },
  { id: 16, category_name: "Travel", icon: "" },
  { id: 17, category_name: "Art", icon: "" },
  { id: 18, category_name: "Nature", icon: "" },
  { id: 19, category_name: "Cars", icon: "" },
];
